---
{{if .Values._000_commonConfig.infrastructure.kafka.enabled}}

kind: Secret
apiVersion: v1
metadata:
  name: {{include "united-manufacturing-hub.fullname" .}}-kafka-broker-secrets
  labels:
    {{- include "united-manufacturing-hub.labels.kafka" . | nindent 4}}
type: Opaque
stringData:
  ca.crt: |
    {{.Values._000_commonConfig.infrastructure.kafka.CACert | nindent 4}}
  tls.crt: |
    {{.Values._000_commonConfig.infrastructure.kafka.cert | nindent 4}}
  tls.key: |
    {{.Values._000_commonConfig.infrastructure.kafka.privkey | nindent 4}}

{{end}}
